# Calls all playbooks to:
# deploy nsx manager, deploy control cluster,
# prepare hosts, configure VLXLAN, Transport Zone
# and finally deploys a logical topology
#
- hosts: localhost
  tasks:
#- debug:
#        msg: "Deploy NSX Manager and configures SSO"
#- include: bd_deploy_nsxm.yml

#- debug:
#        msg: "Deploy Control Cluster"
#- include: bd_controller.yml

- debug:
        msg: "Prepare clusters for VXLAN/DFW"
- include: bd_cluster_prep.yml

- debug:
        msg: "Build multi teir topology and configure ospf"
- include: bd_full_top.yml
