# Calls all playbooks to:
# deploy nsx manager, deploy control cluster,
# prepare hosts, configure VLXLAN, Transport Zone
# and finally deploys a logical topology
#
---
- hosts: localhost
  tasks:
  - include: bd_deploy_nsxm.yml
  - include: bd_controller.yml
  - include: bd_cluster_prep.yml
  - include: bd_full_top.yml
