# Calls all Playbook/roles to:
# deploy nsx manager, deploy control cluster,
# prepare hosts, configure VLXLAN, Transport Zone
# and finally deploys a logical topology
#
---
- name: Deploy NSX Manager OVA
  hosts: localhost
  gather_facts: False
  roles:
    - role: bd_nsx_manager
  tags: nsx_mgmt
- name: Deploy NSX Control Plane
  hosts: localhost
  gather_facts: False
  roles:
    - role: bd_nsx_control
  tags: nsx_ctrl
- name: Deploy NSX Date Plane
  hosts: localhost
  gather_facts: False
  roles:
    - role: bd_nsx_data
  tags: nsx_data
