---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - bd_cluster_prep.yml
  tasks:
  - name: gather moid for cluster 1
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      datacenter_name: "{{ vcenter_dc }}"
      cluster_name: "{{ vcenter_mgmt_cluster }}"
      validate_certs: False
    register: gather_moids_cl_1
    tags: moids
  - name: gather moid for cluster 2
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      datacenter_name: "{{ vcenter_dc }}"
      cluster_name: "{{ vcenter_comp_cluster }}"
      validate_certs: False
    register: gather_moids_cl_2
    tags: moids
  - name: gather moid for portgroup cluster 1
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      datacenter_name: "{{ vcenter_dc }}"
      portgroup_name: "{{ vcenter_mgmt_pg }}"
      validate_certs: False
    register: gather_moids_pg_1
    tags: moids
  - name: gather moid for portgroup cluster 2
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      datacenter_name: "{{ vcenter_dc }}"
      portgroup_name: "{{ vcenter_comp_pg }}"
      validate_certs: False
    register: gather_moids_pg_2
    tags: moids
  - name: Cluster 1 preparation
    nsx_cluster_prep:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      cluster_moid: "{{ gather_moids_cl_1.object_id }}"
    register: cluster_prep
  - name: Cluster 2 preparation
    nsx_cluster_prep:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      cluster_moid: "{{ gather_moids_cl_2.object_id }}"
    register: cluster_prep
  #- debug: var=cluster_prep
# Create IP Pool for VXLAN VTEPS
  - name: Cluster IP Pool creation
    nsx_ippool:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      name: "{{ clu_pool_name }}"
      start_ip: "{{ clu_st_ip }}"
      end_ip: "{{ clu_end_ip }}"
      prefix_length: "{{ clu_pre_len }}"
      gateway: "{{ clu_pool_gw }}"
      dns_server_1: "{{ clu_dns1 }}"
    register: create_ip_pool
# VXLAN Preparation
  - name: Cluster 1 VXLAN Preparation
    nsx_vxlan_prep:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      cluster_moid: "{{ gather_moids_cl_1.object_id }}"
      dvs_moid: "{{ gather_moids_pg_1.object_id }}"
      ippool_id: "{{ create_ip_pool.ippool_id }}"
      #vlan_id: 100
      #vmknic_count: 1
      #teaming: 'ETHER_CHANNEL'
      #mtu: 9000
    register: vxlan_prep
  - name: Cluster 2 VXLAN Preparation
    nsx_vxlan_prep:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      cluster_moid: "{{ gather_moids_cl_2.object_id }}"
      dvs_moid: "{{ gather_moids_pg_2.object_id }}"
      ippool_id: "{{ create_ip_pool.ippool_id }}"
      #vlan_id: 100
      #vmknic_count: 1
      #teaming: 'ETHER_CHANNEL'
      #mtu: 9000
    register: vxlan_prep
# Add VNI Range
  tasks:
  - name: Segment Pool Configuration
    nsx_segment_id_pool:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
    register: create_segment_pool
# Defauls to Unicast and VNI of 5000 - 15000
# Add transport zone
  - name: Transport Zone Creation
    nsx_transportzone:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: 'present'
      name: "{{ TZ }}"
      controlplanemode: "{{ CP_mode }}"
      description: 'Ansible Transport Zone'
      cluster_moid_list:
        - "{{ gather_moids_cl_1.object_id }}"
        - "{{ gather_moids_cl_2.object_id }}"
    register: transport_zone
