---
- hosts: localhost
  gather_facts: False
  vars_files:
     - bd_deploy_nsxm_ans.yml
  tasks:
  - name: deploy nsx-man
    nsx_deploy_ova:
      ovftool_path: '/usr/bin'
      datacenter: "{{ vcenter_dc }}"
      datastore: "{{ vcenter_datastore }}"
      portgroup: "{{ nsxm_portgrp }}"
      cluster: "{{ vcenter_mgmt_cluster }}"
      vmname: "{{ nsx_name }}"
      hostname: "{{ nsx_hostname }}"
      dns_server: "{{ dns_svr }}"
      ntp_server: "{{ ntp_svr }}"
      dns_domain: "{{ dns_domain }}"
      gateway: "{{ gw }}"
      ip_address: "{{ ip }}"
      netmask: "{{ mask }}"
      admin_password: "{{ admin_pw }}"
      enable_password: "{{ enable_pw }}"
      path_to_ova: "{{ ova_path }}"
      ova_file: "{{ ova_name }}"
      vcenter: "{{ vcenter }}"
      vcenter_user: "{{ vcenter_user }}"
      vcenter_passwd: "{{ vcenter_pw }}"
    register: deploy_nsx_man

  - name: NSX Manager SSO Registration
    nsx_sso_registration:
      state: present
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      sso_lookupservice_url: " {{ sso_url }}"
      sso_lookupservice_port: "{{ sso_port }}"
      sso_lookupservice_server: "{{ sso_server }}"
      sso_admin_username: "{{ sso_admin }}"
      sso_admin_password: "{{ sso_pw }}"
      #sso_certthumbprint: 'DE:D7:57:DC:D3:E4:40:4E:AA:4A:3A:56:91:B0:48:92:6E:68:E6:03'
      accept_all_certs: true
    register: register_to_sso
