---
- hosts: localhost
  gather_facts: False
  vars_files:
     - bd_new_nsx_answer.yml
  tasks:
  - name: deploy nsx-man
    nsx_deploy_ova:
      ovftool_path: '/usr/bin'
      datacenter: "{{ vcenter_dc }}"
      datastore: "{{ vcenter_datastore }}"
      portgroup: "{{ nsxm_portgrp }}"
      cluster: "{{ vcenter_mgmt_cluster }}"
      vmname: "{{ nsx_name }}"
      hostname: "{{ nsx_hostname }}"
      dns_server: "{{ dns_svr }}"
      ntp_server: "{{ ntp_svr }}"
      dns_domain: "{{ dns_domain }}"
      gateway: "{{ gw }}"
      ip_address: "{{ ip }}"
      netmask: "{{ mask }}"
      admin_password: "{{ admin_pw }}"
      enable_password: "{{ enable_pw }}"
      path_to_ova: "{{ ova_path }}"
      ova_file: "{{ ova_name }}"
      vcenter: "{{ vcenter }}"
      vcenter_user: "{{ vcenter_user }}"
      vcenter_passwd: "{{ vcenter_pw }}"
    register: deploy_nsx_man

#  - debug: var=deploy_nsx_man
