
---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - bd_ippool_ans.yml
  tasks:
  - name: Cluster IP Pool creation
    nsx_ippool:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      name: "{{ clu_pool_name }}"
      start_ip: "{{ clu_st_ip }}"
      end_ip: "{{ clu_end_ip }}"
      prefix_length: "{{ clu_pre_len }}"
      gateway: "{{ clu_pool_gw }}"
      dns_server_1: "{{ clu_dns1 }}"
    register: create_ip_pool
