---
# vars file for bd_nsx_data
#DLR Network details. Note Transport is used for DLR to ESG connectivity
dlr_networks:
    app1: {name: 'App1-Net', ip: '172.16.8.1', network: '172.16.8.0/24', prefix_len: 24, logical_switch: 'app1', iftype: 'internal'}
    app2: {name: 'App2-Net', ip: '172.16.9.1', network: '172.16.9.0/24', prefix_len: 24, logical_switch: 'app2', iftype: 'internal'}
    db1: {name: 'Db1-Net', ip: '172.16.10.1', network: '172.16.10.0/24', prefix_len: 24, logical_switch: 'db1', iftype: 'internal'}
    web1: {name: 'Web1-Net', ip: '172.16.11.1', network: '172.16.11.0/24', prefix_len: 24, logical_switch: 'web1', iftype: 'internal'}
    web2: {name: 'Web2-Net', ip: '172.16.12.1', network: '172.16.12.0/24', prefix_len: 24, logical_switch: 'web2', iftype: 'internal'}
    web3: {name: 'Web3-Net', ip: '172.16.13.1', network: '172.16.13.0/24', prefix_len: 24, logical_switch: 'web3', iftype: 'internal'}
    transit_net: {name: 'transit_net', ip: '172.24.1.2', network: '172.24.1.2/29', prefix_len: 29, logical_switch: 'transit_net', iftype: 'uplink'}

# ESG connected networks. Uplink is VLAN backed and should be accessible for next hop router.
esg_networks:
    uplink: {name: 'uplink', ip: '192.168.100.3', prefix_len: 24, portgroup_id: "{{ gather_moids_upl_pg.object_id }}", iftype: 'uplink'}
    transit_net: {name: 'transit_net', ip: '172.24.1.1', prefix_len: 29, logical_switch: 'transit_net', iftype: 'internal'}

# Transport Zone for logical networks
transport_zone: 'Ansible_TZ'
cp_mode: "UNICAST_MODE"

#vCenter connection Details.
vcenter: "vc-l-01a.corp.local"
vcenter_user: "administrator@vsphere.local"
vcenter_pwd: "VMware1!"
vcenter_dc: "NSX Site A"
vcenter_datastore: "ds-site-a-nfs01"
vcenter_edge_cluster: "Management and Edge Cluster"

#NSX Manager connection details and RMAL spec location.
nsxmanager_spec:
  raml_file: '/home/nsxguy/nsxraml/nsxvapi.raml'
  host: 'nsxmgr-l-01a'
  user: 'admin'
  password: 'VMware1!'

# ESG Config
esg_name: 'ansibleESG'
esg_admin_username: 'admin'
esg_admin_password: 'VMware1!VMware1!'
firewall_on_off: 'false'
ha_enable: 'false'
esg_size: 'compact'
gw_ip: '192.168.100.1'
esg_router_id: '192.168.100.3'
uplink_portgroup: "Mgmt_Edge_VDS_Mgmt"
esg_nth_ospf_area: '0'
esg_nth_ospf_nic: '0'
esg_sth_ospf_area: '10'
esg_sth_ospf_nic: '1'


#DLR Config
dlr_name: 'ansibleDLR'
dlr_admin_username: 'admin'
dlr_admin_password: 'VMware1!VMware1!'
dlr_ha: 'false'
dlr_router_id: '172.24.1.3'
dlr_for_addr: '172.24.1.2'
dlr_nth_ospf_area: '10'
