---
# tasks file for bd_nsx_control
  - name: Controller IP Pool creation
    nsx_ippool:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      name: "{{ ctl_pool_name }}"
      start_ip: "{{ ctl_st_ip }}"
      end_ip: "{{ ctl_end_ip }}"
      prefix_length: "{{ ctl_pre_len }}"
      gateway: "{{ ctl_pool_gw }}"
      dns_server_1: "{{ ctl_dns1 }}"
    register: create_ip_pool
#  - debug: var=create_ip_pool.ippool_id

  - name: gather moid for cl
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      datacenter_name: "{{ vcenter_dc }}"
      cluster_name: "{{ vcenter_mgmt_cluster }}"
      validate_certs: False
    register: gather_moids_cl
    tags: moids
  - name: gather moid for ds
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      datacenter_name: "{{ vcenter_dc }}"
      datastore_name: "{{ vcenter_datastore }}"
      validate_certs: False
    register: gather_moids_ds
    tags: moids
  - name: gather moid for controller portgroup
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      datacenter_name: "{{ vcenter_dc }}"
      portgroup_name: "{{ ctl_portgroup }}"
      validate_certs: False
    register: gather_moids_pg
    tags: moids
# Using single mode as timers for controller creation time out in my nested lab. 3x single works fine.
  - name: Controller 1 Creation
    nsx_controllers:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      deploytype: "{{ dep_type }}"
      syslog_server: "{{ syslog }}"
      ippool_id: "{{ create_ip_pool.ippool_id }}"
      resourcepool_moid: "{{ gather_moids_cl.object_id }}"
      datastore_moid: "{{ gather_moids_ds.object_id }}"
      network_moid: "{{ gather_moids_pg.object_id }}"
      password: "{{ ctl_pw }}"
    register: create_controller_1
  #- debug: var=create_controller_1
  - name: Controller 2 Creation
    nsx_controllers:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      deploytype: "{{ dep_type }}"
      syslog_server: "{{ syslog }}"
      ippool_id: "{{ create_ip_pool.ippool_id }}"
      resourcepool_moid: "{{ gather_moids_cl.object_id }}"
      datastore_moid: "{{ gather_moids_ds.object_id }}"
      network_moid: "{{ gather_moids_pg.object_id }}"
      password: "{{ ctl_pw }}"
    register: create_controller_2
  - name: Controller 3 Creation
    nsx_controllers:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      deploytype: "{{ dep_type }}"
      syslog_server: "{{ syslog }}"
      ippool_id: "{{ create_ip_pool.ippool_id }}"
      resourcepool_moid: "{{ gather_moids_cl.object_id }}"
      datastore_moid: "{{ gather_moids_ds.object_id }}"
      network_moid: "{{ gather_moids_pg.object_id }}"
      password: "{{ ctl_pw }}"
    register: create_controller_3
  - name: gather moid for cluster 1
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      datacenter_name: "{{ vcenter_dc }}"
      cluster_name: "{{ vcenter_mgmt_cluster }}"
      validate_certs: False
    register: gather_moids_cl_1
    tags: moids
  - name: gather moid for cluster 2
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      datacenter_name: "{{ vcenter_dc }}"
      cluster_name: "{{ vcenter_comp_cluster }}"
      validate_certs: False
    register: gather_moids_cl_2
    tags: moids
  - name: gather moid for VDS cluster 1
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      datacenter_name: "{{ vcenter_dc }}"
      dvs_name: "{{ vcenter_mgmt_vds }}"
      validate_certs: False
    register: gather_moids_vds_1
    tags: moids
  - name: gather moid for VDS cluster 2
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      datacenter_name: "{{ vcenter_dc }}"
      dvs_name: "{{ vcenter_comp_vds }}"
      validate_certs: False
    register: gather_moids_vds_2
    tags: moids
  - name: Cluster 1 preparation
    nsx_cluster_prep:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      cluster_moid: "{{ gather_moids_cl_1.object_id }}"
    register: cluster_prep
  - name: Cluster 2 preparation
    nsx_cluster_prep:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      cluster_moid: "{{ gather_moids_cl_2.object_id }}"
    register: cluster_prep
# Create IP Pool for VXLAN VTEPS
  - name: Cluster IP Pool creation
    nsx_ippool:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      name: "{{ clu_pool_name }}"
      start_ip: "{{ clu_st_ip }}"
      end_ip: "{{ clu_end_ip }}"
      prefix_length: "{{ clu_pre_len }}"
      gateway: "{{ clu_pool_gw }}"
      dns_server_1: "{{ clu_dns1 }}"
    register: create_ip_pool
# VXLAN Preparation
  - name: Cluster 1 VXLAN Preparation
    nsx_vxlan_prep:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      cluster_moid: "{{ gather_moids_cl_1.object_id }}"
      dvs_moid: "{{ gather_moids_vds_1.object_id }}"
      ippool_id: "{{ create_ip_pool.ippool_id }}"
      #vlan_id: 100
      #vmknic_count: 1
      #teaming: 'ETHER_CHANNEL'
      #mtu: 9000
    register: vxlan_prep
  - name: Cluster 2 VXLAN Preparation
    nsx_vxlan_prep:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      cluster_moid: "{{ gather_moids_cl_2.object_id }}"
      dvs_moid: "{{ gather_moids_vds_2.object_id }}"
      ippool_id: "{{ create_ip_pool.ippool_id }}"
      #vlan_id: 100
      #vmknic_count: 1
      #teaming: 'ETHER_CHANNEL'
      #mtu: 9000
    register: vxlan_prep
# Add VNI Range
  - name: Segment Pool Configuration
    nsx_segment_id_pool:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
    register: create_segment_pool
# Defauls to Unicast and VNI of 5000 - 15000
# Add transport zone
  - name: Transport Zone Creation
    nsx_transportzone:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: 'present'
      name: "{{ TZ }}"
      controlplanemode: "{{ CP_mode }}"
      description: 'Ansible Transport Zone'
      cluster_moid_list:
        - "{{ gather_moids_cl_1.object_id }}"
        - "{{ gather_moids_cl_2.object_id }}"
    register: transport_zone
  - debug: var=transport_zone
